/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict-local
 * @format
 */

import type {WPTFixtures} from './WPTTestHarness';

let fixtures: WPTFixtures;
try {
  // $FlowExpectedError[untyped-import] JSON cannot carry a Flow declaration.
  // $FlowExpectedError[cannot-resolve-module] Generated by sync.js, not committed.
  fixtures = require('./generated/wpt-fixtures.json') as WPTFixtures;
} catch {
  throw new Error(
    'wpt-fixtures.json not found. Run: node scripts/web-platform-tests/sync.js --wpt-root=/path/to/wpt',
  );
}

export default fixtures;
